export { default as Footer } from './Theme_1/Footer'
export { default as Header } from './Theme_1/Header'
export { default as Intro } from './Theme_1/Intro'
export { default as Skills } from './Theme_1/Skills'
export { default as Card } from './Theme_1/Card'
export { default as Contact } from './Theme_1/Contact'
export {default as Github} from './Theme_1/Github'
export {default as Experience} from './Theme_1/Experience'